### PR TITLE
Add Cardinals

### PR DESCRIPTION
**Pull request by alicelite**
Cardinals Balance Display
Cardinals Transaction History
Cardinals Transaction Details

### CODE REVIEW

**Comment by Pimax1** [comment]
WDOGE token is not doginals, cardinals are not doginals. Your drc20 is not drc20

**Comment by dpaydrc20** [comment]
This would be a bad move. This is Doginals
https://github.com/apezord/ord-dogecoin 
https://github.com/apezord/doginals

**Comment by blockchaindad** [comment]
Not a good look for Dogecoin

1st Adding Cardinals would cause chaos and confusion on account of the cardinals token standard being called DRC-20, a token standard that already exist on the base layer that is DOGE.

2nd Cardinals is not a layer one protocol and requires users to bridge their Dogecoin off chain where safety is not guaranteed.

Bridging any coin to layer 2 comes with inherent risk and as such should be taken seriously to protect users from funds being lost, stolen, spent.

Let’s be responsible about this and make sure the future of Doge is on Doge. 

-Do Only Good Everyday

**Comment by GreatApe42069** [comment]
3af1633b3a210a25820a86b2311d5c39
Not a Good Look! The Đogecoin and Đoginal Community won't support this move. Tried to slip cardinals right in there 🤔🧐

**Comment by Ser-GY** [comment]
What is the purpose and goal of accepting such a pull into the repo? As I see in their repo there is nothing open source but instead a well detailed abstract. 
While this is a much better documentation of what is possible through inscribing various data sets/types on Doge, it does not share the source code.
How does a node this? Are we meant to only have inscriptions indexed if the Unelon central service?
I also do not see a difference in the deployment json structure of a "Cardinal" drc20 deploy or mint vs a "Doginal" drc20 deploy or mint. How does an indexer recognize the difference? Is there supposed to be a difference. Perhaps this is an optimization to the previously inscribed and traded Drc20 tokens which used the minter built by Apezord and used widely across doggy market, ordinalswallet, and Doge labs marketplace. If it is I would love to see this specified and then fully opened up with the source code necessary to run on my node.
Thank you!

**Comment by kinaskitaro** [comment]
Doginals are a piece of crap from DogeCoin
If DogeCoin and MyDogeWallet don't support Cardinal, we, the Chinese, will take you to court. You are just as shitty as Doginals.

**Comment by Pimax1** [comment]
It seems there's been a misunderstanding. MyDoge announced support for Doginals, not Cardinals, and it's crucial to make this distinction clear to avoid misleading our community.

I must address the mention of legal action. There is no basis for a lawsuit in this situation, as protocol support decisions are within the rights of MyDoge and are made in the best interest of its users. Threats of legal action are not only baseless but also reflect poorly on those who issue them, showing their true colors.

Furthermore, attempting to merge Cardinals under the guise of the recent Doginal support through a pull request can be seen as deceptive. This kind of behavior is concerning and could be construed as an attempt to scam users, which is something the "DOGE" ethos strongly condemn.

> Doginals are a piece of crap from DogeCoin If DogeCoin and MyDogeWallet don't support Cardinal, we, the Chinese, will take you to court. You are just as shitty as Doginals.

**Comment by Pimax1** [comment]
Just realized the Cardinals' support was planned with prior talks? 
@alexanvl, when they started this protocol, it was very infamous from its inception. Can you provide more details on whether MyDoge will implement it? This PR was done very quickly after the Doginals support announcement...

**Comment by satoshidoge** [comment]
Cardinals Protocol is an advanced blockchain solution designed to enhance and extend the Dogecoin ecosystem. Here are its key features:

Decentralized Operations: All processes within the Cardinals protocol are executed without any centralized authority, ensuring complete decentralization.

Simplified Transactions: Supports various operations, including DRC20 tokens, NFTs, and decentralized trading, all achievable with minimal transactions.

Enhanced Security: Utilizes signature encryption for all metadata content and supports multi-signature verification, ensuring robust security.

Scalability: Facilitates fully open token issuance, minting, and transfers through on-chain metadata transactions, with only necessary gas fees required.

Standardization: Provides open-source tools for protocol compliance detection, enabling the creation of consistent and unified databases.

Cross-Chain Support: Plans for cross-indexing with other blockchains (e.g., Bitcoin) to enable cross-chain asset operations, optimizing UTXO space and enhancing interaction flexibility.

Ecosystem Development: Focuses on growing the developer ecosystem, promoting protocol scalability and standardization, and fostering innovation within the Dogecoin community.

On-Chain Exchange: Powers a decentralized exchange (DEX) for DRC20 token trading, order execution, and liquidity management, similar to Uniswap.

The Cardinals Protocol not only enhances Dogecoin's functionality and security but also provides a flexible and powerful platform for developers and users.

**Comment by Ser-GY** [comment]
Why isn't the source code available to verify these claims?

**Comment by Ser-GY** [comment]
How can I run this on my node?

**Comment by Pimax1** [comment]
Good sales speech but I would strongly advise to exercise a VERY HIGH level of caution. 

My personal observations:

Single centralized marketplace. 

Centralized token WDOGE to interact directly with l1. 

Used purposely the "drc-20" trending name created for doginals protocol to confuse and appropriate users. 

suspicious repo with missing or obfuscated code:
image

All marketing speeches seems dishonest and not founded. The communications are complete hogwash in almost all aspects:
https://medium.com/@unielon/an-introduction-to-drc-20-based-on-the-cardinals-protocol-a8a32ba3846

image
image
image

False paid reviews spamming youtube.

Very aggressive founder who constantly propagates lies about his own protocol and against doginals. He has always been heavily criticized.

MyDoge can review the security of cardinals and its benefits if any. Don't say you have not been warned.

**Comment by Pimax1** [comment]
Initially criticized for not being truly on dogecoin and being a fake "ordinals" protocol on dogecoin. they are now trying hard to dismiss this.

**Comment by Ser-GY** [comment]
Dogi was deployed on March 11th, 2023 as the first DRC20 token. Cardinals claims to have created the DRC20 protocol in May of 2033. You tell me who has provenance of the term "Drc20"?

**Comment by Ser-GY** [comment]
Well done for putting this together in a clear and easy way to follow while showing proof of claims.

**Comment by Pimax1** [comment]
In case you try to edit your medium article or delete it, don't worry, its all saved already. So much disinformation and lies in a single page. Clearly the founder is dishonest and not to be trusted.

Also its very interesting to see people reporting a wasm file in your wallet?? you cannot do worst than this in terms of security, backdoor to drain everyone? 

image

**Comment by Pimax1** [comment]
in this review they show dogelabs tokens and website in the background, but ask you to download unielon.
https://www.youtube.com/watch?v=uMtrGd0N7lQ
This is clear deception and fraudulent activity. No honest and legit protocol would pay people to purposely deceive. All other reviews are clearly paid ones.

Forgot to mention, when they launched, I immediately noticed the twitter account was bought with false followers. They were running on ETHF and trying to pretend to be the dogecoin version of ordinals. I immediately considered this project as a scam the first day and never looked back. Sad to see they are still around tricking people.

MyDoge, it would irresponsible to announce supporting a malicious protocol.

**Comment by Pimax1** [comment]
FRAUD:
https://www.youtube.com/watch?v=uMtrGd0N7lQ
This review pretends that dogelabs was the old plateform and unielon was the new one, pretends that you can transfer from dpal wallet to unielon. 

Also don't be tricked by the fake followers on their twitter account. I noticed on the day they launch the twitter accounts were bought with fake followers. They were running on ETHF and pretended to be ordinals on dogecoin. I never looked back at this scam.  Sad to see they are still around tricking people.

MyDoge, it would be irresponsible to support a malicious protocol that has tried to steal all legit doginals users from its inception.

**Comment by zsaiwj** [comment]
Add dunes  https://github.com/sirduney/dunes-cli  dogecoin runes
From #doginals protocol

**Comment by satoshidoge** [comment]
Cardinals Protocol introduces several innovative features to the Dogecoin ecosystem:

Dynamic inscription Handling: Cardinals allows for dynamic metadata, enabling more complex and flexible transactions that can evolve over time, enhancing the functionality of tokens and assets on the Dogecoin chain.

Efficient Data Storage: By optimizing how data is stored and managed on the blockchain, Cardinals reduces storage requirements and increases the efficiency of data retrieval and processing.

Advanced Staking Mechanisms: Cardinals implements sophisticated staking protocols, allowing users to earn rewards through a variety of staking options, thus incentivizing long-term engagement and participation in the network.

Programmable Smart Contracts: The protocol supports advanced programmable smart contracts, enabling more complex and customizable interactions between users and applications within the Dogecoin ecosystem.

Seamless Integration with Other Ecosystems: Cardinals is designed to easily integrate with other blockchain ecosystems, facilitating smooth interoperability and the potential for cross-chain applications without compromising the integrity of the Dogecoin network.

Enhanced User Experience: With streamlined transaction processes and reduced fees, Cardinals improves the overall user experience, making it easier and more cost-effective to participate in the Dogecoin network.

Robust Governance Model: Cardinals introduces a robust governance framework that allows the community to participate in decision-making processes, ensuring that the protocol evolves in a way that reflects the needs and desires of its users.

Innovative Token Models: The protocol supports the creation of new and innovative token models, including deflationary tokens, governance tokens, and utility tokens, providing more options for developers and users.

These innovations position Cardinals as a transformative protocol for the Dogecoin ecosystem, driving forward the capabilities and adoption of Dogecoin in the broader blockchain landscape.

**Comment by minidogenft** [comment]
why did cardinals buy  "https://drc20.org/"  which is pointing to the cardinals indexer, while they perfectly know that "drc-20.org" is dogelabs website? 
just a "-" difference. 
People with good intentions do not use such deceptive practices to mislead users. period.

**Comment by dpaydrc20** [comment]
Cardinals and Unielon along with DPAL cause a massive inscription loss almost 5m doge. This happened shortly after the split we directly confronted dev's and they blamed it on user errors when in fact it was just a cover up.  Everything ended up going straight thru this wallet. DJfU2p6woQ9GiBdiXsWZWJnJ9uDdZfSSNC Also if you paste it in X you can see comments. https://x.com/search?q=DJfU2p6woQ9GiBdiXsWZWJnJ9uDdZfSSNC&src=typed_query

**Comment by minidogenft** [comment]
This news is a result of the "Cardinals" protocol's attempts to now deceive all Dogecoin users:

https://u.today/dogecoin-doge-crucial-alert-issued-heres-why

The @dogefdn Twitter account was created by the Cardinals team to promote cardinals. Originally, it promoted only Unielon and Cardinals, but they've now fully committed to impersonating the Dogecoin Foundation. As if attempting to defraud Doginals users wasn't enough, they are now targeting the broader Dogecoin community.

This is what you're dealing with when it comes to Cardinals.

**Comment by ad576** [comment]
> Cardinals 和 Unielon 以及 DPAL 造成了巨大的铭文损失，近 500 万 doge。这件事发生在分裂后不久，我们直接与开发人员对峙，他们将其归咎于用户错误，而事实上这只是一个掩饰。所有东西最终都直接进入了这个钱包。DJfU2p6woQ9GiBdiXsWZWJnJ9uDdZfSSNC 此外，如果您将其粘贴到 X 中，您可以看到评论。https [://x.com/search? q=DJfU2p6woQ9GiBdiXsWZWJnJ9uDdZfSSNC&src=typed_query](https://x.com/search?q=DJfU2p6woQ9GiBdiXsWZWJnJ9uDdZfSSNC&src=typed_query)

This is dogim’s DPAY wallet. Can the user blame others for the losses caused by not choosing to withdraw money from Binance Exchange to his own wallet?

**Comment by ad576** [comment]
> 此消息是“Cardinals”协议试图欺骗所有狗狗币用户的结果：
> 
> https://u.today/dogecoin-doge-crucial-alert-issued-heres-why
> 
> @dogefdn Twitter 帐户由 Cardinals 团队创建，用于宣传 Cardinals。最初，它只宣传 Unielon 和 Cardinals，但现在他们已完全致力于冒充 Dogecoin 基金会。似乎试图欺骗 Doginals 用户还不够，他们现在将目标转向更广泛的 Dogecoin 社区。
> 
> 当谈到红雀队时，这就是你要处理的事情。

The account profile clearly states that it is a third-party foundation. Does this mean that Dogecoin can only have one foundation?

> 此消息是“Cardinals”协议试图欺骗所有狗狗币用户的结果：
> 
> https://u.today/dogecoin-doge-crucial-alert-issued-heres-why
> 
> @dogefdn Twitter 帐户由 Cardinals 团队创建，用于宣传 Cardinals。最初，它只宣传 Unielon 和 Cardinals，但现在他们已完全致力于冒充 Dogecoin 基金会。似乎试图欺骗 Doginals 用户还不够，他们现在将目标转向更广泛的 Dogecoin 社区。
> 
> 当谈到红雀队时，这就是你要处理的事情。

账号简介明确说明是第三方基金会，难道狗狗币只能拥有一个基金会？

**Pull request closed without merging**
